TodoApp/urls.py
from TodoApp import views
from django.urls import path



urlpatterns = [
    
    path('',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

    path('cbvhome/',views.Tasklistview.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.Taskdetailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.Taskupdateview.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.Taskdeleteview.as_view(),name='cbvdelete'),


]

TodoProject/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('TodoApp.urls'))
]

TodoApp/models.py
from django.db import models


# Create your models here.
class Todolist(models.Model):
    name = models.CharField(max_length=150)
    date = models.DateField()
    priority = models.IntegerField()

    def __str__(self):
        return self.name

TodoApp/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from . form import Todoform
from . models import Todolist

#generic views imports

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView ,UpdateView
#create views via generic views


class Tasklistview(ListView):
    model= Todolist
    template_name= 'home.html'
    context_object_name= 'tasks'


class Taskdetailview(DetailView):
    model= Todolist
    template_name= 'details.html'
    context_object_name= 'tasks'


class Taskupdateview(UpdateView):
    model= Todolist
    template_name= 'update.html'
    context_object_name= 'tasks'
    fields = ('name','date','priority')

    def get_success_url(self) :
        return reverse_lazy('cbvdetail',kwargs={'pk':self.object.id})
        
class Taskdeleteview(DeleteView):
    model= Todolist
    context_object_name= 'tasks'
    template_name= 'delete.html'
    success_url=reverse_lazy('cbvhome')

# Create your views here.normal functional way
def home(request):
    data=Todolist.objects.all()
    return render(request,'home.html',{'tasks':data})


#add task to to do list function
def add(request):
    if request.method=='POST':
        n=request.POST.get('name','')
        d=request.POST.get('date','')
        p=request.POST.get('priority','')
        task=Todolist(name=n,date=d,priority=p)
        task.save()
        return redirect('/')
    data=Todolist.objects.all()
    return render(request,'home.html',{'tasks':data})
        

#delete task to to do list function
def update(request,id):   

    task=Todolist.objects.get(id=id)
    form=Todoform(request.POST or None,instance=task)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request,'update.html',{'form':form,'task':task})    


#update task to to do list function
def delete(request,id):
    task=Todolist.objects.get(id=id)
    if request.method=='POST':
        task.delete()
        return redirect('/')
    return render(request,'delete.html',{'task':task})        

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>ToDo app</title>
</head>
<style>
    #f{
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        flex-direction: column;
    }
    #f>p{
        font-weight: bold;
        font-family: monospace;
        font-size: 15px;
        display: flex;
        align-items: center;
        justify-content: space-between;
    }
  #id_name,#id_date,#id_priority{
    width: 70%;
        border: 0;
        outline: none;
        border-bottom: 2px solid grey;
    }
    .update_form{
        display: grid;
        place-items: center;
        color: #000;
        background-color: #fffefe;
    }
</style>
<body style="background-color: rgb(235, 235, 235);">
    <div class="container" >
        <div class="banner " style="height:60px;background: linear-gradient(90deg, #FC466B 0%, #3F5EFB 100%);display: grid;place-items: center;" >
            <div class="banner-title" style="color: white;font-size:xx-large;font-family:monospace;font-weight: bold;">Todo App</div>
        </div>
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
<div class="container"
    style="font-size: 25px; display:grid;place-items:center;color: rgb(56, 37, 3);letter-spacing: 2px;font-weight: bold;">
    <p class="my-5"> delete the task: '{{tasks.name}}?</p>
    <div action="" method="post" class="container my-5 mb-5">
        <div class="row ">
            <div class="col-md-6 mb-4  d-flex align-items-center justify-content-center ">
                <form action="" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn-danger" style="width: 150px ;border-radius:10px;">delete</button>
                </form>
            </div>
            <div class="col-md-6   d-flex align-items-center justify-content-center mb-4">
                <a href="{% url 'add' %}"><button type="disabled" class="btn-success"
                        style="width: 150px;border-radius:10px;">Home</button></a>
            </div>
        </div>
    </DIV>
</div>

{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="row my-3">
    <!-- to do form  -->

    <div class="col-md-5 col-lg-5 col-sm-10 mb-3">
        <form class='px-3' method="post" style="box-shadow:0 0 10px rgb(78, 78, 78) ;
             border-radius:10px; 
             padding:10px;background-color:rgb(255, 255, 255) ;
             border: 2px solid grey;">

            {% csrf_token %}
            <div class="mb-2 ">
                <label  class="form-label"
                    style='color:green;letter-spacing:2px;font-weight:bold'>Task Name:</label>
                <input type="text" class="form-control" placeholder="Task 1..." name="name" required>
            </div>
            <div class="mb-2 form-group">
                <label  class="form-label"
                    style='color:green;letter-spacing:2px;font-weight:bold'>Date:</label>
                <input type="date" class="form-control" placeholder="yyy-mm-dd" name="date" required>
            </div>
            <div class="mb-2 form-group">
                <label  class="form-label"
                    style='color:green;letter-spacing:2px;font-weight:bold'>priority:</label>
                <input type="number" class="form-control" placeholder="1" name="priority" required>
            </div>
            <div class="mb-1 d-flex align-items-center justify-content-center">
                <a href="{% url 'add' %}"><button type="submit" class="btn-primary"> Add Task</button></a>
            </div>
        </form>
    </div>

    <!-- to do form  -->

    <div class="col-md-2 col-lg-2 col-sm-0">
    </div>
    <!-- task list  -->

    <div class="col-md-5 col-lg-5 col-sm-10 text-align-center ">

        {% for i in tasks %}
        <div class="card mb-3 "
            style="border-radius: 10px;box-shadow:inset 0 0 10px rgb(78, 78, 78) ;border: 2px solid green;">
            <div class="card-body">
                <p class="card-title"> <b> Name: {{i.name}}</b></p>
                <p class="card-title"><b>Date: {{i.date}}</b></p>
                <p class="card-title"><b>Priority: {{i.priority}}</b></p>
                <a href="{% url 'update' i.id %}" class="btn btn-warning">Update</a>
                <a href="{% url 'delete' i.id %}" class="btn btn-danger">Done</a>

            </div>
        </div>
        {% endfor %}
    </div>
    <!-- task list  -->

</div>

{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="row my-3">
    <!-- to do form  -->

    <div class="col-md-3 col-lg-3 col-sm-0  "></div>

    <div class="col-md-6 col-lg-6 col-sm-10 text-align-center ">

      
        <div class="card mb-3 "
            style="border-radius: 10px;box-shadow:inset 0 0 10px rgb(78, 78, 78) ;border: 2px solid green;">
            <div class="card-body">
                <p class="card-title"> <b> Name: {{tasks.name}}</b></p>
                <p class="card-title"><b>Date: {{tasks.date}}</b></p>
                <p class="card-title"><b>Priority: {{tasks.priority}}</b></p>
                <a href="{% url 'update' tasks.id %}" class="btn btn-warning">Update</a>
                <a href="{% url 'delete' tasks.id %}" class="btn btn-danger">Done</a>

            </div>
        </div>
    </div>
    <!-- task list  -->
    <div class="col-md-3 col-lg-3 col-sm-0  "></div>

</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="row my-3">
    <!-- to do form  -->

    <div class="col-md-5 col-lg-5 col-sm-10 mb-3">
        <form class='px-3' method="post" style="box-shadow:0 0 10px rgb(78, 78, 78) ;
             border-radius:10px; 
             padding:10px;background-color:rgb(255, 255, 255) ;
             border: 2px solid grey;">

            {% csrf_token %}
            <div class="mb-2 ">
                <label for="exampleFormControlInput1" class="form-label"
                    style='color:green;letter-spacing:2px;font-weight:bold'>Task Name:</label>
                <input type="text" class="form-control" placeholder="Task 1..." name="name" required>
            </div>
            <div class="mb-2 form-group">
                <label for="exampleFormControlInput1" class="form-label"
                    style='color:green;letter-spacing:2px;font-weight:bold'>Date:</label>
                <input type="date" class="form-control" placeholder="yyy-mm-dd" name="date" required>
            </div>
            <div class="mb-2 form-group">
                <label for="exampleFormControlInput1" class="form-label"
                    style='color:green;letter-spacing:2px;font-weight:bold'>priority:</label>
                <input type="number" class="form-control" placeholder="1" name="priority" required>
            </div>
            <div class="mb-1 d-flex align-items-center justify-content-center" >
                <a href="{% url 'add' %}"><button type="submit" class="btn-primary"> Add Task</button></a>
            </div>
        </form>
    </div>

    <!-- to do form  -->

    <div class="col-md-2 col-lg-2 col-sm-0">
    </div>
    <!-- task list  -->

    <div class="col-md-5 col-lg-5 col-sm-10 text-align-center ">

        {% for i in tasks %}
        <div class="card mb-3 "
            style="border-radius: 10px;box-shadow:inset 0 0 10px rgb(78, 78, 78) ;border: 2px solid green;">
            <div class="card-body">
                <p class="card-title"> <b> Name: {{i.name}}</b></p>
                <p class="card-title"><b>Date: {{i.date}}</b></p>
                <p class="card-title"><b>Priority: {{i.priority}}</b></p>
                <a href="{% url 'update' i.id %}" class="btn btn-warning">Update</a>
                <a href="{% url 'delete' i.id %}" class="btn btn-danger">Done</a>

            </div>
        </div>
        {% endfor %}
    </div>
    <!-- task list  -->

</div>


{% endblock %}

templates/update.html
{% extends 'base.html' %}
{% block body %}

<div class="update_form col-12 my-3 container" style="border:2px solid green ;">
   <p style="font-size:20px;letter-spacing:2px;color: darkslategray;font-weight: bold;text-align: center;" class="mt-3"> update this task:'{{tasks.name}}'?</p>
    <hr style="width:50% ;color: blueviolet;height: 4px;">
    <form action="" method="post"  id="f">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn-warning my-4"style='width:200px'>update</button>
</form>
</div>

{% endblock %}